import os

BASE_DIR = r"c:\Users\Pinak chimurkar\DSA"
phase1_dir = os.path.join(BASE_DIR, "Phase 01 Two Pointers & Sliding Window")
os.makedirs(phase1_dir, exist_ok=True)

p1_finish = [
    # 026
    {
        "id": "026", "name": "Minimum Size Subarray Sum", "lc_num": 209, "difficulty": "Medium",
        "url": "https://leetcode.com/problems/minimum-size-subarray-sum/",
        "q_statement": "Given an array of positive integers `nums` and a positive integer `target`, return the **minimal length** of a subarray whose sum is greater than or equal to `target`. If there is no such subarray, return `0` instead.",
        "examples": "Input: target = 7, nums = [2,3,1,2,4,3]\nOutput: 2\nExplanation: Subarray [4,3] has minimal length 2 under target 7.",
        "constraints": "- 1 <= target <= 10^9\n- 1 <= nums.length <= 10^5\n- 1 <= nums[i] <= 10^5",
        "bf_pattern": "Nested Loops Subarray Check",
        "bf_intuition": "Calculate sum of all subarrays [i...j] and track minimal length where sum >= target.",
        "bf_algo": "1. min_len = INF.\n2. Loop i from 0 to n-1, loop j from i to n-1.\n3. Compute sum(nums[i...j]); if sum >= target: min_len = min(min_len, j - i + 1).\n4. Return min_len == INF ? 0 : min_len.",
        "bf_code": "#include <vector>\n#include <algorithm>\nclass Solution {\npublic:\n    int minSubArrayLen(int target, const std::vector<int>& nums) {\n        int min_len = 1e9, n = nums.size();\n        for (int i = 0; i < n; ++i) {\n            int sum = 0;\n            for (int j = i; j < n; ++j) {\n                sum += nums[j];\n                if (sum >= target) {\n                    min_len = std::min(min_len, j - i + 1);\n                    break;\n                }\n            }\n        }\n        return min_len == 1e9 ? 0 : min_len;\n    }\n};",
        "bf_tc": "O(N^2)", "bf_sc": "O(1)",
        "bf_why_not_opt": "Nested loops calculate redundant sums. Sliding Window achieves linear O(N) time.",
        "opt_pattern": "Variable-Size Sliding Window (Dynamic Shrink)",
        "opt_concept": "Expand right pointer to increase window sum until sum >= target. Then shrink left pointer to find minimal valid length.",
        "opt_obs": "Since all elements are positive, adding elements increases sum and shrinking window decreases sum monotonically.",
        "opt_intuition": "Expand right. Whenever sum >= target, update min_len and shrink left while sum >= target.",
        "opt_algo": "1. left = 0, sum = 0, min_len = INF.\n2. Loop right from 0 to n-1:\n   a. sum += nums[right]\n   b. While sum >= target:\n      min_len = min(min_len, right - left + 1)\n      sum -= nums[left++]\n3. Return min_len == INF ? 0 : min_len.",
        "opt_code": "#include <vector>\n#include <algorithm>\nclass Solution {\npublic:\n    int minSubArrayLen(int target, const std::vector<int>& nums) {\n        int left = 0, sum = 0;\n        int min_len = 1e9;\n        \n        for (int right = 0; right < (int)nums.size(); ++right) {\n            sum += nums[right];\n            while (sum >= target) {\n                min_len = std::min(min_len, right - left + 1);\n                sum -= nums[left++];\n            }\n        }\n        return min_len == 1e9 ? 0 : min_len;\n    }\n};",
        "opt_dry_run": "target=7, [2,3,1,2,4,3] -> r=3 sum=8>=7 -> min_len=4, shrink -> r=4 [3,1,2,4] sum=10>=7 -> shrink -> [1,2,4] sum=7>=7 -> min_len=3...",
        "opt_tc": "O(N)", "opt_sc": "O(1)",
        "opt_why_opt": "Each element is processed at most twice (once by right, once by left) taking linear O(N) time.",
        "opt_mistakes": "Forgetting return 0 when no subarray satisfies condition.",
        "summary": "Find minimum size subarray with sum >= target using variable sliding window in O(N) time.",
        "pattern_rec": "Subarray sum >= target with positive numbers -> Variable Sliding Window.",
        "clues": "Minimal length, sum >= target, positive elements.",
        "diagram": "Window [2,3,1,2] sum=8>=7 -> shrink left -> [3,1,2] sum=6 < 7 -> expand right",
        "alt_sol": "Binary Search on prefix sums O(N log N).",
        "edge_cases": "Total sum < target (returns 0), single element >= target.",
        "tips": "Highlight why positive numbers condition allows monotonic window shrinking.",
        "similar": "LeetCode #713, #862, #904",
        "rev_notes": "left=0, sum=0, min_len=INF. Loop right=0..n-1: sum += nums[right]. While sum>=target: min_len=min(min_len, right-left+1), sum -= nums[left++]. O(N) time, O(1) space."
    },
    # 027
    {
        "id": "027", "name": "Permutation in String", "lc_num": 567, "difficulty": "Medium",
        "url": "https://leetcode.com/problems/permutation-in-string/",
        "q_statement": "Given two strings `s1` and `s2`, return `true` if `s2` contains a permutation of `s1`, or `false` otherwise. In other words, return `true` if one of `s1`'s permutations is the substring of `s2`.",
        "examples": "Input: s1 = \"ab\", s2 = \"eidbaooo\"\nOutput: true\nExplanation: s2 contains one permutation of s1 (\"ba\").",
        "constraints": "- 1 <= s1.length, s2.length <= 10^4\n- s1 and s2 consist of lowercase English letters.",
        "bf_pattern": "Generate Permutations",
        "bf_intuition": "Generate all permutations of s1 and search each permutation in s2.",
        "bf_algo": "1. Generate permutations of s1.\n2. For each perm: if s2.find(perm) != string::npos return true.\n3. Return false.",
        "bf_code": "#include <string>\n#include <algorithm>\nclass Solution {\npublic:\n    bool checkInclusion(std::string s1, std::string s2) {\n        std::sort(s1.begin(), s1.end());\n        do {\n            if (s2.find(s1) != std::string::npos) return true;\n        } while (std::next_permutation(s1.begin(), s1.end()));\n        return false;\n    }\n};",
        "bf_tc": "O(N1! * N2)", "bf_sc": "O(1)",
        "bf_why_not_opt": "Factorial complexity O(N1!). Frequency map sliding window achieves linear O(N2) time.",
        "opt_pattern": "Fixed-Size Sliding Window (Frequency Count)",
        "opt_concept": "Window size in s2 must equal s1.length(). Maintain frequency difference between s1 and current window in s2.",
        "opt_obs": "A window in s2 is a permutation of s1 if and only if character frequency counts match exactly.",
        "opt_intuition": "Maintain array count of size 26. Count s1 chars (+1) and first window of s2 (-1). Slide window of length s1.len across s2 updating count array.",
        "opt_algo": "1. If s1.len > s2.len return false.\n2. int count[26] = {0}.\n3. For i=0..s1.len-1: count[s1[i]-'a']++, count[s2[i]-'a']--.\n4. If all count elements are 0 return true.\n5. For i=s1.len..s2.len-1:\n   count[s2[i]-'a']--, count[s2[i - s1.len]-'a']++\n   if all count elements are 0 return true.\n6. Return false.",
        "opt_code": "#include <string>\n#include <vector>\nclass Solution {\nprivate:\n    bool isZero(const int count[26]) {\n        for (int i = 0; i < 26; ++i) if (count[i] != 0) return false;\n        return true;\n    }\npublic:\n    bool checkInclusion(const std::string& s1, const std::string& s2) {\n        int len1 = s1.length(), len2 = s2.length();\n        if (len1 > len2) return false;\n        \n        int count[26] = {0};\n        for (int i = 0; i < len1; ++i) {\n            count[s1[i] - 'a']++;\n            count[s2[i] - 'a']--;\n        }\n        if (isZero(count)) return true;\n        \n        for (int i = len1; i < len2; ++i) {\n            count[s2[i] - 'a']--;\n            count[s2[i - len1] - 'a']++;\n            if (isZero(count)) return true;\n        }\n        return false;\n    }\n};",
        "opt_dry_run": "s1=\"ab\", s2=\"eidbaooo\" -> window 0..1 \"ei\" -> window 2..3 \"db\" -> window 3..4 \"ba\" (matches!) -> true",
        "opt_tc": "O(N2)", "opt_sc": "O(1)",
        "opt_why_opt": "Single pass sliding window O(N2) with 26-element array taking O(1) auxiliary space.",
        "opt_mistakes": "Not checking len1 > len2, off-by-one window index calculations.",
        "summary": "Check if s2 contains a permutation of s1 using fixed-size sliding window with character frequency matching in O(N2) time.",
        "pattern_rec": "Substring anagram/permutation search -> Fixed Sliding Window Frequency Array.",
        "clues": "Substring permutation, fixed length s1.length().",
        "diagram": "s1: \"ab\" (a:1, b:1)\ns2: e i d [b a] o o o -> window \"ba\" matches frequency of s1!",
        "alt_sol": "Match counter tracking count of matches (0 to 26).",
        "edge_cases": "s1 longer than s2, s1 == s2, single char strings.",
        "tips": "Mention tracking match count variable to optimize check from 26 operations to O(1).",
        "similar": "LeetCode #438: Find All Anagrams, LeetCode #76: Minimum Window Substring",
        "rev_notes": "If s1.len > s2.len return false. Fixed window of size s1.len. Track count[26] char diffs. Slide window: count[s2[i]]--, count[s2[i-len1]]++. O(N2) time, O(1) space."
    },
    # 028
    {
        "id": "028", "name": "Find All Anagrams in a String", "lc_num": 438, "difficulty": "Medium",
        "url": "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
        "q_statement": "Given two strings `s` and `p`, return an array of all the start indices of `p`'s anagrams in `s`. You may return the answer in any order.",
        "examples": "Input: s = \"cbaebabacd\", p = \"abc\"\nOutput: [0,6]\nExplanation: The substring at index 0 is \"cba\" (anagram of \"abc\"), at index 6 is \"bac\".",
        "constraints": "- 1 <= s.length, p.length <= 3 * 10^4\n- s and p consist of lowercase English letters.",
        "bf_pattern": "Sort Substrings",
        "bf_intuition": "Extract every substring of length p.len in s, sort it, and compare with sorted p.",
        "bf_algo": "1. Sort string p.\n2. For i from 0 to s.len - p.len: sub = s[i...i+p.len-1], sort sub, if sub == sorted_p add i.",
        "bf_code": "#include <vector>\n#include <string>\n#include <algorithm>\nclass Solution {\npublic:\n    std::vector<int> findAnagrams(std::string s, std::string p) {\n        std::vector<int> res;\n        int s_len = s.length(), p_len = p.length();\n        if (s_len < p_len) return res;\n        std::sort(p.begin(), p.end());\n        for (int i = 0; i <= s_len - p_len; ++i) {\n            std::string sub = s.substr(i, p_len);\n            std::sort(sub.begin(), sub.end());\n            if (sub == p) res.push_back(i);\n        }\n        return res;\n    }\n};",
        "bf_tc": "O(N * P log P)", "bf_sc": "O(P)",
        "bf_why_not_opt": "Sorting substrings takes O(N * P log P). Sliding window frequency map reduces to linear O(N) time.",
        "opt_pattern": "Fixed-Size Sliding Window (Frequency Vector)",
        "opt_concept": "Maintain sliding window of size p.length() in s. Compare character frequency vector.",
        "opt_obs": "Two strings are anagrams if and only if their 26-element character frequency vectors are identical.",
        "opt_intuition": "Maintain 2 frequency vectors of size 26 (`p_freq` and `window_freq`). Slide window across `s`, updating `window_freq` in O(1). When `p_freq == window_freq`, record start index.",
        "opt_algo": "1. If s.len < p.len return {}.\n2. Build p_freq and window_freq for first p.len chars.\n3. If p_freq == window_freq add 0 to result.\n4. Loop i from p.len to s.len - 1:\n   window_freq[s[i]-'a']++\n   window_freq[s[i - p.len]-'a']--\n   if p_freq == window_freq: add i - p.len + 1 to result.\n5. Return result.",
        "opt_code": "#include <vector>\n#include <string>\nclass Solution {\npublic:\n    std::vector<int> findAnagrams(const std::string& s, const std::string& p) {\n        std::vector<int> result;\n        int s_len = s.length(), p_len = p.length();\n        if (s_len < p_len) return result;\n        \n        std::vector<int> p_freq(26, 0), window_freq(26, 0);\n        for (int i = 0; i < p_len; ++i) {\n            p_freq[p[i] - 'a']++;\n            window_freq[s[i] - 'a']++;\n        }\n        \n        if (p_freq == window_freq) result.push_back(0);\n        \n        for (int i = p_len; i < s_len; ++i) {\n            window_freq[s[i] - 'a']++;\n            window_freq[s[i - p_len] - 'a']--;\n            if (p_freq == window_freq) {\n                result.push_back(i - p_len + 1);\n            }\n        }\n        return result;\n    }\n};",
        "opt_dry_run": "s=\"cbaebabacd\", p=\"abc\" -> window 0..2 (\"cba\") matches -> push 0. window 6..8 (\"bac\") matches -> push 6.",
        "opt_tc": "O(N)", "opt_sc": "O(1) auxiliary space",
        "opt_why_opt": "Single pass O(N) time with 26-element vector comparison taking O(1) space.",
        "opt_mistakes": "Forgetting boundary check when s.length() < p.length().",
        "summary": "Find all starting indices of anagrams of p in s using a fixed-size sliding window with character frequency arrays in O(N) time.",
        "pattern_rec": "Find all occurrences of anagram substring -> Fixed Sliding Window.",
        "clues": "Find all start indices, anagram matching, fixed window size = p.len.",
        "diagram": "s = [c b a] e b a [b a c] d -> matches at indices 0 and 6",
        "alt_sol": "Sliding window with single match count tracker.",
        "edge_cases": "s shorter than p, s and p equal length.",
        "tips": "In C++, `vector<int> == vector<int>` compares elements directly in O(26) = O(1) time.",
        "similar": "LeetCode #567: Permutation in String, LeetCode #3: Longest Substring Without Repeating",
        "rev_notes": "If s.len < p.len return {}. p_freq & window_freq size 26. Init first p.len chars. Slide i=p.len..s.len-1: add s[i], remove s[i-p.len]. If match -> push i-p.len+1. O(N) time, O(1) space."
    },
    # 029
    {
        "id": "029", "name": "Minimum Window Substring", "lc_num": 76, "difficulty": "Hard",
        "url": "https://leetcode.com/problems/minimum-window-substring/",
        "q_statement": "Given two strings `s` and `t` of lengths `m` and `n` respectively, return the **minimum window substring** of `s` such that every character in `t` (including duplicates) is included in the window. If there is no such substring, return the empty string `\"\"`.",
        "examples": "Input: s = \"ADOBECODEBANC\", t = \"ABC\"\nOutput: \"BANC\"\nExplanation: The minimum window substring \"BANC\" includes 'A', 'B', and 'C' from string t.",
        "constraints": "- m == s.length, n == t.length\n- 1 <= m, n <= 10^5\n- s and t consist of uppercase and lowercase English letters.",
        "bf_pattern": "All Substrings Check",
        "bf_intuition": "Generate all possible substrings of s, check if each contains all required characters of t.",
        "bf_algo": "1. min_len = INF, start_idx = -1.\n2. For i from 0 to m-1, for j from i to m-1:\n   if s[i...j] contains all chars of t: if j-i+1 < min_len: min_len = j-i+1, start_idx = i.\n3. Return s.substr(start_idx, min_len).",
        "bf_code": "#include <string>\n#include <unordered_map>\nclass Solution {\nprivate:\n    bool containsAll(const std::unordered_map<char, int>& s_map, const std::unordered_map<char, int>& t_map) {\n        for (auto& [c, count] : t_map) {\n            if (s_map.count(c) == 0 || s_map.at(c) < count) return false;\n        }\n        return true;\n    }\npublic:\n    std::string minWindow(const std::string& s, const std::string& t) {\n        std::unordered_map<char, int> t_map;\n        for (char c : t) t_map[c]++;\n        int min_len = 1e9, start = -1;\n        for (int i = 0; i < s.length(); ++i) {\n            std::unordered_map<char, int> s_map;\n            for (int j = i; j < s.length(); ++j) {\n                s_map[s[j]]++;\n                if (containsAll(s_map, t_map)) {\n                    if (j - i + 1 < min_len) {\n                        min_len = j - i + 1;\n                        start = i;\n                    }\n                    break;\n                }\n            }\n        }\n        return start == -1 ? \"\" : s.substr(start, min_len);\n    }\n};",
        "bf_tc": "O(M^2 * |T|)", "bf_sc": "O(|S| + |T|)",
        "bf_why_not_opt": "Polynomial time O(M^2 * |T|). Two Pointers Variable Sliding Window achieves O(M + N).",
        "opt_pattern": "Variable-Size Sliding Window (Expand / Shrink with Required Counter)",
        "opt_concept": "Expand right pointer until window contains all chars of t. Then shrink left pointer to find minimum valid window.",
        "opt_obs": "Maintain `required` count of characters still needed. When `required == 0`, current window [left...right] is valid.",
        "opt_intuition": "Build frequency map `map` for `t`. Expand `right`: if `map[s[right]] > 0` decrement `required`. Decrement `map[s[right]]`. While `required == 0`: update min window, increment `map[s[left]]`, if `map[s[left]] > 0` increment `required`, increment `left`.",
        "opt_algo": "1. Build frequency map target_count of size 128 for t.\n2. required = t.length(), min_len = INF, start_idx = 0.\n3. Loop right from 0 to s.length() - 1:\n   if target_count[s[right]] > 0: required--\n   target_count[s[right]]--\n   while required == 0:\n     if right - left + 1 < min_len: min_len = right - left + 1, start_idx = left\n     target_count[s[left]]++\n     if target_count[s[left]] > 0: required++\n     left++\n4. Return min_len == INF ? \"\" : s.substr(start_idx, min_len).",
        "opt_code": "#include <string>\n#include <vector>\nclass Solution {\npublic:\n    std::string minWindow(const std::string& s, const std::string& t) {\n        std::vector<int> target_count(128, 0);\n        for (char c : t) target_count[c]++;\n        \n        int left = 0, min_len = 1e9, start_idx = 0;\n        int required = t.length();\n        \n        for (int right = 0; right < (int)s.length(); ++right) {\n            if (target_count[s[right]] > 0) {\n                required--;\n            }\n            target_count[s[right]]--;\n            \n            while (required == 0) {\n                if (right - left + 1 < min_len) {\n                    min_len = right - left + 1;\n                    start_idx = left;\n                }\n                target_count[s[left]]++;\n                if (target_count[s[left]] > 0) {\n                    required++;\n                }\n                left++;\n            }\n        }\n        return min_len == 1e9 ? \"\" : s.substr(start_idx, min_len);\n    }\n};",
        "opt_dry_run": "s=\"ADOBECODEBANC\", t=\"ABC\" -> expand until valid window \"ADOBEC\" -> shrink -> ... -> \"BANC\" (len 4)",
        "opt_tc": "O(M + N)", "opt_sc": "O(1) (128 ASCII array)",
        "opt_why_opt": "Single pass expansion and contraction where left and right pointers move at most M steps in linear time.",
        "opt_mistakes": "Not handling negative counts in frequency map properly when shrinking window.",
        "summary": "Find minimum substring of s containing all characters of t using variable sliding window with required character counter in O(M+N) time.",
        "pattern_rec": "Minimum window substring covering target set -> Variable Sliding Window (Expand / Shrink).",
        "clues": "Minimum window, substring containing all characters, Hard problem.",
        "diagram": "Expand right until all t chars present -> Shrink left until missing a t char -> Repeat",
        "alt_sol": "Filtered sliding window skipping non-t characters.",
        "edge_cases": "t longer than s, no valid window, t has duplicate characters.",
        "tips": "Explain clearly why `target_count[c]` can become negative (represents extra characters in current window).",
        "similar": "LeetCode #30: Substring with Concatenation of All Words, LeetCode #567: Permutation in String",
        "rev_notes": "target_count size 128 for t. required=t.len. Expand right: if target_count[s[r]]>0 required--; target_count[s[r]]--. While required==0: update min window, target_count[s[l]]++, if target_count[s[l]]>0 required++; l++. O(M+N) time, O(1) space."
    },
    # 030
    {
        "id": "030", "name": "Longest Repeating Character Replacement", "lc_num": 424, "difficulty": "Medium",
        "url": "https://leetcode.com/problems/longest-repeating-character-replacement/",
        "q_statement": "You are given a string `s` and an integer `k`. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most `k` times. Return the length of the longest substring containing the same letter you can get after performing the above operations.",
        "examples": "Input: s = \"AABABBA\", k = 1\nOutput: 4\nExplanation: Replace one 'B' with 'A' to get \"AAAA\". Substring length = 4.",
        "constraints": "- 1 <= s.length <= 10^5\n- 0 <= k <= s.length\n- s consists of uppercase English letters.",
        "bf_pattern": "All Substrings Check",
        "bf_intuition": "Generate all substrings s[i...j], find max frequency char in substring. If (len - max_freq) <= k, valid.",
        "bf_algo": "1. max_len = 0.\n2. For i from 0 to n-1, for j from i to n-1:\n   len = j - i + 1, max_freq = max_char_count(s[i...j])\n   if (len - max_freq) <= k: max_len = max(max_len, len).\n3. Return max_len.",
        "bf_code": "#include <string>\n#include <vector>\n#include <algorithm>\nclass Solution {\npublic:\n    int characterReplacement(const std::string& s, int k) {\n        int max_len = 0, n = s.length();\n        for (int i = 0; i < n; ++i) {\n            std::vector<int> count(26, 0);\n            int max_freq = 0;\n            for (int j = i; j < n; ++j) {\n                count[s[j] - 'A']++;\n                max_freq = std::max(max_freq, count[s[j] - 'A']);\n                if ((j - i + 1) - max_freq <= k) {\n                    max_len = std::max(max_len, j - i + 1);\n                }\n            }\n        }\n        return max_len;\n    }\n};",
        "bf_tc": "O(N^2)", "bf_sc": "O(1)",
        "bf_why_not_opt": "O(N^2) quadratic time. Sliding Window with max frequency tracking achieves O(N).",
        "opt_pattern": "Variable-Size Sliding Window (Max Frequency Tracking)",
        "opt_concept": "Window validity condition: `(window_length - max_frequency_character) <= k`.",
        "opt_obs": "In any window [left...right], to make all characters identical, we change the characters that are NOT the most frequent character. Number of replacements needed = `(right - left + 1) - max_freq`.",
        "opt_intuition": "Expand `right`. Track `max_freq` of any single character in current window. If `(right - left + 1) - max_freq > k`, shrink `left` by 1.",
        "opt_algo": "1. count array of size 26, left = 0, max_freq = 0, max_len = 0.\n2. Loop right from 0 to n-1:\n   count[s[right]-'A']++\n   max_freq = max(max_freq, count[s[right]-'A'])\n   if (right - left + 1) - max_freq > k:\n     count[s[left]-'A']--\n     left++\n   max_len = max(max_len, right - left + 1).\n3. Return max_len.",
        "opt_code": "#include <string>\n#include <vector>\n#include <algorithm>\nclass Solution {\npublic:\n    int characterReplacement(const std::string& s, int k) {\n        std::vector<int> count(26, 0);\n        int left = 0, max_freq = 0, max_len = 0;\n        \n        for (int right = 0; right < (int)s.length(); ++right) {\n            count[s[right] - 'A']++;\n            max_freq = std::max(max_freq, count[s[right] - 'A']);\n            \n            while ((right - left + 1) - max_freq > k) {\n                count[s[left] - 'A']--;\n                left++;\n            }\n            max_len = std::max(max_len, right - left + 1);\n        }\n        return max_len;\n    }\n};",
        "opt_dry_run": "s=\"AABABBA\", k=1 -> r=3 (\"AABA\") max_freq=3 ('A') -> len-max_freq = 4-3 = 1 <= 1 (Valid! len=4)",
        "opt_tc": "O(N)", "opt_sc": "O(1)",
        "opt_why_opt": "Single pass O(N) linear time with 26-element array taking O(1) space.",
        "opt_mistakes": "Thinking max_freq must be decremented when shrinking left (max_freq only needs to be updated when a new max frequency is found).",
        "summary": "Find longest substring of identical letters after at most k replacements using sliding window in O(N) time.",
        "pattern_rec": "At most K character modifications -> Variable Sliding Window (len - max_freq <= k).",
        "clues": "Replace at most k characters, longest substring with identical letters.",
        "diagram": "Window [A A B A] -> len=4, max_freq(A)=3 -> replacements needed = 4-3 = 1 <= k(1) (Valid)",
        "alt_sol": "Binary Search on window length O(N log N).",
        "edge_cases": "k=0 (longest consecutive identical string), k >= s.length().",
        "tips": "Explain why `max_freq` does NOT need to shrink when left pointer advances.",
        "similar": "LeetCode #1004: Max Consecutive Ones III, LeetCode #2024",
        "rev_notes": "count array size 26. left=0, max_freq=0. Loop right: count[s[r]]++, max_freq=max(max_freq, count[s[r]]). If (right-left+1)-max_freq > k: count[s[l]]--, left++. O(N) time, O(1) space."
    },
    # 031
    {
        "id": "031", "name": "Fruit Into Baskets", "lc_num": 904, "difficulty": "Medium",
        "url": "https://leetcode.com/problems/fruit-into-baskets/",
        "q_statement": "You have two baskets, and each basket can only hold a **single type of fruit**. You can pick at most two types of fruits from a row of trees represented by an array `fruits`. Return the maximum number of fruits you can pick.",
        "examples": "Input: fruits = [1,2,3,2,2]\nOutput: 4\nExplanation: Pick from trees [2,3,2,2]. Length = 4.",
        "constraints": "- 1 <= fruits.length <= 10^5\n- 0 <= fruits[i] < fruits.length",
        "bf_pattern": "Nested Loops Subarray Check",
        "bf_intuition": "Check every subarray fruits[i...j], count distinct fruit types. Track max length of subarray with <= 2 types.",
        "bf_algo": "1. max_len = 0.\n2. For i from 0 to n-1, for j from i to n-1:\n   set types = set(fruits[i...j])\n   if types.size() <= 2: max_len = max(max_len, j - i + 1).\n3. Return max_len.",
        "bf_code": "#include <vector>\n#include <unordered_set>\n#include <algorithm>\nclass Solution {\npublic:\n    int totalFruit(const std::vector<int>& fruits) {\n        int max_len = 0, n = fruits.size();\n        for (int i = 0; i < n; ++i) {\n            std::unordered_set<int> types;\n            for (int j = i; j < n; ++j) {\n                types.insert(fruits[j]);\n                if (types.size() > 2) break;\n                max_len = std::max(max_len, j - i + 1);\n            }\n        }\n        return max_len;\n    }\n};",
        "bf_tc": "O(N^2)", "bf_sc": "O(1)",
        "bf_why_not_opt": "Quadratic time O(N^2). HashMap Sliding Window achieves linear O(N) time.",
        "opt_pattern": "Variable-Size Sliding Window (At Most K Distinct Elements)",
        "opt_concept": "Problem reduces to: **Find longest subarray containing at most 2 distinct integers**.",
        "opt_obs": "Maintain a hash map of character counts in current window. If map size > 2, shrink left pointer until map size <= 2.",
        "opt_intuition": "Expand right pointer, insert fruits[right] into map. When map size > 2, decrement map[fruits[left]], remove from map if count reaches 0, and increment left.",
        "opt_algo": "1. unordered_map<int, int> count.\n2. left = 0, max_len = 0.\n3. Loop right from 0 to n-1:\n   count[fruits[right]]++\n   while count.size() > 2:\n     count[fruits[left]]--\n     if count[fruits[left]] == 0: count.erase(fruits[left])\n     left++\n   max_len = max(max_len, right - left + 1).\n4. Return max_len.",
        "opt_code": "#include <vector>\n#include <unordered_map>\n#include <algorithm>\nclass Solution {\npublic:\n    int totalFruit(const std::vector<int>& fruits) {\n        std::unordered_map<int, int> basket;\n        int left = 0, max_len = 0;\n        \n        for (int right = 0; right < (int)fruits.size(); ++right) {\n            basket[fruits[right]]++;\n            while (basket.size() > 2) {\n                basket[fruits[left]]--;\n                if (basket[fruits[left]] == 0) {\n                    basket.erase(fruits[left]);\n                }\n                left++;\n            }\n            max_len = std::max(max_len, right - left + 1);\n        }\n        return max_len;\n    }\n};",
        "opt_dry_run": "[1,2,3,2,2] -> r=0(1) basket{1:1} -> r=1(2) basket{1:1, 2:1} -> r=2(3) basket{1:1,2:1,3:1} > 2 -> shrink left until basket{2:1,3:1} -> r=4 max_len=4",
        "opt_tc": "O(N)", "opt_sc": "O(1) (At most 3 keys in map)",
        "opt_why_opt": "Single pass O(N) linear time with O(1) space since map holds at most 3 entries.",
        "opt_mistakes": "Forgetting to `erase()` map key when count reaches 0 (causes map size to remain > 2).",
        "summary": "Find max fruits collected into 2 baskets by computing longest subarray with at most 2 distinct elements in O(N) time.",
        "pattern_rec": "Longest subarray with at most K distinct elements -> Variable Sliding Window + Map.",
        "clues": "2 baskets (K=2 distinct types), contiguous trees (subarray), maximize total count.",
        "diagram": "Window [1, 2, 3] -> 3 distinct types! -> shrink left -> Window [2, 3, 2, 2] (4 elements)",
        "alt_sol": "Sliding window with non-shrinking window optimization.",
        "edge_cases": "Array size <= 2, all elements identical ([1,1,1]).",
        "tips": "Identify that problem is an exact alias for 'Longest Subarray with at most 2 Distinct Elements'.",
        "similar": "LeetCode #159: Longest Substring with At Most Two Distinct Characters, LeetCode #340",
        "rev_notes": "Map basket tracks counts. left=0. Loop right: basket[fruits[r]]++. While basket.size()>2: basket[fruits[l]]--, erase if 0, l++. max_len=max(max_len, r-l+1). O(N) time, O(1) space."
    },
    # 032
    {
        "id": "032", "name": "Max Consecutive Ones III", "lc_num": 1004, "difficulty": "Medium",
        "url": "https://leetcode.com/problems/max-consecutive-ones-iii/",
        "q_statement": "Given a binary array `nums` and an integer `k`, return the maximum number of consecutive `1`s in the array if you can flip at most `k` `0`s.",
        "examples": "Input: nums = [1,1,1,0,0,0,1,1,1,1,0], k = 2\nOutput: 6\nExplanation: [1,1,1,0,0,1,1,1,1,1,1] (flipped 2 zeroes at indices 5 and 10). Max length = 6.",
        "constraints": "- 1 <= nums.length <= 10^5\n- nums[i] is either 0 or 1\n- 0 <= k <= nums.length",
        "bf_pattern": "All Substrings Check",
        "bf_intuition": "For every subarray nums[i...j], count zeroes. If zero_count <= k, track max length j - i + 1.",
        "bf_algo": "1. max_len = 0.\n2. For i from 0 to n-1, for j from i to n-1:\n   zeroes = count zeroes in nums[i...j]\n   if zeroes <= k: max_len = max(max_len, j - i + 1).\n3. Return max_len.",
        "bf_code": "#include <vector>\n#include <algorithm>\nclass Solution {\npublic:\n    int longestOnes(const std::vector<int>& nums, int k) {\n        int max_len = 0, n = nums.size();\n        for (int i = 0; i < n; ++i) {\n            int zeroes = 0;\n            for (int j = i; j < n; ++j) {\n                if (nums[j] == 0) zeroes++;\n                if (zeroes <= k) max_len = std::max(max_len, j - i + 1);\n                else break;\n            }\n        }\n        return max_len;\n    }\n};",
        "bf_tc": "O(N^2)", "bf_sc": "O(1)",
        "bf_why_not_opt": "Quadratic time O(N^2). Sliding Window tracking zero count achieves linear O(N) time.",
        "opt_pattern": "Variable-Size Sliding Window (Zero Counter)",
        "opt_concept": "Maintain sliding window [left...right]. Track number of 0s in current window. Window is valid if `zero_count <= k`.",
        "opt_obs": "Problem equals: **Find longest subarray containing at most K zeroes**.",
        "opt_intuition": "Expand `right`. If `nums[right] == 0`, increment `zero_count`. While `zero_count > k`, if `nums[left] == 0` decrement `zero_count`, and increment `left`.",
        "opt_algo": "1. left = 0, zero_count = 0, max_len = 0.\n2. Loop right from 0 to n-1:\n   if nums[right] == 0: zero_count++\n   while zero_count > k:\n     if nums[left] == 0: zero_count--\n     left++\n   max_len = max(max_len, right - left + 1).\n3. Return max_len.",
        "opt_code": "#include <vector>\n#include <algorithm>\nclass Solution {\npublic:\n    int longestOnes(const std::vector<int>& nums, int k) {\n        int left = 0, zero_count = 0, max_len = 0;\n        for (int right = 0; right < (int)nums.size(); ++right) {\n            if (nums[right] == 0) {\n                zero_count++;\n            }\n            while (zero_count > k) {\n                if (nums[left] == 0) {\n                    zero_count--;\n                }\n                left++;\n            }\n            max_len = std::max(max_len, right - left + 1);\n        }\n        return max_len;\n    }\n};",
        "opt_dry_run": "[1,1,1,0,0,0,1,1,1,1,0], k=2 -> r=5 zero_count=3 > 2 -> shrink left past first zero -> r=10 max_len=6",
        "opt_tc": "O(N)", "opt_sc": "O(1)",
        "opt_why_opt": "Single pass O(N) linear time with O(1) space.",
        "opt_mistakes": "Thinking zeroes need to be physically flipped in memory.",
        "summary": "Find maximum consecutive 1s achievable by flipping at most k zeroes using sliding window in O(N) time.",
        "pattern_rec": "At most K zeroes flipped -> Sliding Window (zero_count <= k).",
        "clues": "Binary array, flip at most k zeroes, longest consecutive 1s.",
        "diagram": "Window [1, 1, 1, 0, 0] (2 zeroes <= k=2) -> next 0 makes 3 zeroes -> shrink left",
        "alt_sol": "Non-shrinking window variant (O(N) single pass without inner while loop).",
        "edge_cases": "k = 0 (longest consecutive 1s without flips), array all zeroes, array all ones.",
        "tips": "Emphasize problem equivalence to 'Longest Subarray with at most K zeroes'.",
        "similar": "LeetCode #485: Max Consecutive Ones, LeetCode #424: Longest Repeating Replacement",
        "rev_notes": "left=0, zero_count=0. Loop right: if nums[r]==0 zero_count++. While zero_count>k: if nums[l]==0 zero_count--; l++. max_len=max(max_len, r-l+1). O(N) time, O(1) space."
    }
]

for p_data in p1_finish:
    p_folder = os.path.join(phase1_dir, f"{p_data['id']} {p_data['name']}")
    os.makedirs(p_folder, exist_ok=True)
    
    with open(os.path.join(p_folder, "00_Question.md"), "w", encoding="utf-8") as f:
        f.write(f"# {p_data['id']}. {p_data['name']}\n\n- **Platform**: LeetCode\n- **Problem Number**: #{p_data['lc_num']}\n- **Difficulty**: {p_data['difficulty']}\n- **URL**: [{p_data['name']}]({p_data['url']})\n\n---\n\n## Problem Statement\n\n{p_data['q_statement']}\n\n---\n\n## Examples\n\n{p_data['examples']}\n\n---\n\n## Constraints\n\n{p_data['constraints']}\n")
        
    with open(os.path.join(p_folder, "01_Brute_Force.md"), "w", encoding="utf-8") as f:
        f.write(f"# {p_data['name']}\n\n- **Problem Number**: {p_data['lc_num']}\n- **Platform**: LeetCode #{p_data['lc_num']}\n- **Difficulty**: {p_data['difficulty']}\n- **Pattern**: {p_data['bf_pattern']}\n\n---\n\n## Brute Force Intuition\n\n{p_data['bf_intuition']}\n\n---\n\n## Algorithm\n\n{p_data['bf_algo']}\n\n---\n\n## Code\n\n```cpp\n{p_data['bf_code']}\n```\n\n---\n\n## Time Complexity\n\n- **Time Complexity**: {p_data['bf_tc']}\n\n---\n\n## Space Complexity\n\n- **Space Complexity**: {p_data['bf_sc']}\n\n---\n\n## Why This Approach Is Not Optimal\n\n{p_data['bf_why_not_opt']}\n")

    with open(os.path.join(p_folder, "02_Optimal_Approach.md"), "w", encoding="utf-8") as f:
        f.write(f"# {p_data['name']}\n\n## Pattern Used\n\n- **Pattern**: **{p_data['opt_pattern']}**\n- **Concept**: {p_data['opt_concept']}\n\n---\n\n## Observation\n\n{p_data['opt_obs']}\n\n---\n\n## Intuition\n\n{p_data['opt_intuition']}\n\n---\n\n## Algorithm\n\n{p_data['opt_algo']}\n\n---\n\n## Clean C++17 Solution\n\n```cpp\n{p_data['opt_code']}\n```\n\n---\n\n## Dry Run\n\n{p_data['opt_dry_run']}\n\n---\n\n## Time Complexity\n\n- **Time Complexity**: {p_data['opt_tc']}\n\n---\n\n## Space Complexity\n\n- **Space Complexity**: {p_data['opt_sc']}\n\n---\n\n## Why This is Optimal\n\n{p_data['opt_why_opt']}\n\n---\n\n## Common Mistakes\n\n{p_data['opt_mistakes']}\n")

    with open(os.path.join(p_folder, "03_Explanation.md"), "w", encoding="utf-8") as f:
        f.write(f"# Problem Summary\n\n{p_data['summary']}\n\n---\n\n## Pattern Recognition\n\n{p_data['pattern_rec']}\n\n---\n\n## Important Clues\n\n{p_data['clues']}\n\n---\n\n## Example\n\n```text\n{p_data['diagram']}\n```\n\n---\n\n## Alternative Solutions\n\n{p_data['alt_sol']}\n\n---\n\n## Edge Cases\n\n{p_data['edge_cases']}\n\n---\n\n## Interview Tips\n\n{p_data['tips']}\n\n---\n\n## Similar Problems\n\n{p_data['similar']}\n\n---\n\n## Revision Notes\n\n{p_data['rev_notes']}\n")

print("Generated all remaining Phase 1 problems 026 to 032 successfully!")
