import os

BASE_DIR = r"c:\Users\Pinak chimurkar\DSA"
phase0_dir = os.path.join(BASE_DIR, "Phase 00 Programming Foundation")
phase1_dir = os.path.join(BASE_DIR, "Phase 01 Two Pointers & Sliding Window")

os.makedirs(phase0_dir, exist_ok=True)
os.makedirs(phase1_dir, exist_ok=True)

all_problems = [
    # 003
    {
        "dir": phase0_dir,
        "id": "003",
        "name": "Best Time to Buy and Sell Stock",
        "lc_num": 121, "difficulty": "Easy",
        "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
        "q_statement": "You are given an array `prices` where `prices[i]` is the price of a given stock on the `i`-th day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit you can achieve from this transaction.",
        "examples": "Input: prices = [7,1,5,3,6,4]\nOutput: 5\nExplanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.",
        "constraints": "- 1 <= prices.length <= 10^5\n- 0 <= prices[i] <= 10^4",
        "bf_pattern": "Nested Loops",
        "bf_intuition": "Compare every pair (i, j) with j > i to find max(prices[j] - prices[i]).",
        "bf_algo": "1. Set max_profit = 0.\n2. Loop i, j > i.\n3. Update max_profit.",
        "bf_code": "class Solution {\npublic:\n    int maxProfit(const std::vector<int>& prices) {\n        int max_p = 0;\n        for(int i=0; i<prices.size(); i++)\n            for(int j=i+1; j<prices.size(); j++)\n                max_p = std::max(max_p, prices[j]-prices[i]);\n        return max_p;\n    }\n};",
        "bf_tc": "O(N^2)", "bf_sc": "O(1)",
        "bf_why_not_opt": "Re-checks every pair redundantly. Single pass tracking min price is O(N).",
        "opt_pattern": "Single Pass Tracking / Greedy",
        "opt_concept": "Maintain running min price and max profit in one traversal.",
        "opt_obs": "Profit at day i is prices[i] - min(prices[0...i-1]).",
        "opt_intuition": "Track lowest buy price seen so far. At each day, update min_price and check profit.",
        "opt_algo": "1. min_price = INT_MAX, max_profit = 0.\n2. For each price: min_p = min(min_p, p), max_p = max(max_p, p - min_p).\n3. Return max_p.",
        "opt_code": "class Solution {\npublic:\n    int maxProfit(const std::vector<int>& prices) {\n        int min_price = 1e9, max_profit = 0;\n        for (int price : prices) {\n            min_price = std::min(min_price, price);\n            max_profit = std::max(max_profit, price - min_price);\n        }\n        return max_profit;\n    }\n};",
        "opt_dry_run": "[7,1,5,3,6,4] -> min=1, profit=5",
        "opt_tc": "O(N)", "opt_sc": "O(1)",
        "opt_why_opt": "Single pass O(N) is lower bound as every price must be seen.",
        "opt_mistakes": "Buying after selling or resetting min_price wrongly.",
        "summary": "Track running minimum buy price and maximum profit achieved in single pass.",
        "pattern_rec": "Max profit single transaction -> Running minimum.",
        "clues": "Must buy before sell, 1 transaction allowed.",
        "diagram": "prices:[7,1,5,3,6,4] -> min:1, max_profit:5",
        "alt_sol": "Kadane's algorithm on daily price differences.",
        "edge_cases": "Decreasing prices ([5,4,3,2,1] -> 0), single price ([5] -> 0).",
        "tips": "Mention relation to Kadane's maximum subarray sum.",
        "similar": "LeetCode #122, #123, #188, #309, #53",
        "rev_notes": "min_price = min(min_price, p); max_profit = max(max_profit, p - min_price). O(N) time, O(1) space."
    },
    # 004
    {
        "dir": phase0_dir,
        "id": "004",
        "name": "Contains Duplicate",
        "lc_num": 217, "difficulty": "Easy",
        "url": "https://leetcode.com/problems/contains-duplicate/",
        "q_statement": "Given an integer array `nums`, return `true` if any value appears at least twice in the array, and return `false` if every element is distinct.",
        "examples": "Input: nums = [1,2,3,1]\nOutput: true",
        "constraints": "- 1 <= nums.length <= 10^5\n- -10^9 <= nums[i] <= 10^9",
        "bf_pattern": "Nested Loops",
        "bf_intuition": "Compare every pair for equality.",
        "bf_algo": "1. Outer loop i, inner loop j > i.\n2. If nums[i] == nums[j], return true.",
        "bf_code": "class Solution {\npublic:\n    bool containsDuplicate(const std::vector<int>& nums) {\n        for(int i=0; i<nums.size(); i++)\n            for(int j=i+1; j<nums.size(); j++)\n                if(nums[i] == nums[j]) return true;\n        return false;\n    }\n};",
        "bf_tc": "O(N^2)", "bf_sc": "O(1)",
        "bf_why_not_opt": "Quadratic time. Hash set or sorting reduces time complexity.",
        "opt_pattern": "Hash Set Lookup",
        "opt_concept": "Store seen elements in std::unordered_set.",
        "opt_obs": "If element already in set, duplicate detected.",
        "opt_intuition": "As we iterate, query hash set. If present return true, else insert.",
        "opt_algo": "1. Create unordered_set seen.\n2. For x in nums: if x in seen return true, else insert x.\n3. Return false.",
        "opt_code": "#include <vector>\n#include <unordered_set>\n\nclass Solution {\npublic:\n    bool containsDuplicate(const std::vector<int>& nums) {\n        std::unordered_set<int> seen;\n        for (int x : nums) {\n            if (seen.count(x)) return true;\n            seen.insert(x);\n        }\n        return false;\n    }\n};",
        "opt_dry_run": "[1,2,3,1] -> seen={1,2,3}, 1 exists -> true",
        "opt_tc": "O(N)", "opt_sc": "O(N)",
        "opt_why_opt": "Hash set gives O(1) average lookup/insert time.",
        "opt_mistakes": "Forgetting space complexity of set.",
        "summary": "Check if array contains duplicates using hash set.",
        "pattern_rec": "Uniqueness check -> Hash Set or Sorting.",
        "clues": "Find duplicate values, unsorted input.",
        "diagram": "1 -> 2 -> 3 -> 1 (Duplicate found!)",
        "alt_sol": "Sorting first: O(N log N) time, O(1) space.",
        "edge_cases": "Single element ([1] -> false), empty array, negative numbers.",
        "tips": "Discuss trade-off between Hash Set (O(N) space) and Sorting (O(1) space).",
        "similar": "LeetCode #219, #220, #136, #448, #287",
        "rev_notes": "Use std::unordered_set. Insert while checking. O(N) time, O(N) space."
    },
    # 005
    {
        "dir": phase0_dir,
        "id": "005",
        "name": "Majority Element",
        "lc_num": 169, "difficulty": "Easy",
        "url": "https://leetcode.com/problems/majority-element/",
        "q_statement": "Given an array `nums` of size `n`, return the majority element (element appearing > ⌊n / 2⌋ times).",
        "examples": "Input: nums = [3,2,3]\nOutput: 3",
        "constraints": "- 1 <= n <= 5 * 10^4",
        "bf_pattern": "Hash Map Frequency Counting",
        "bf_intuition": "Count frequency of all numbers and return the one > n/2.",
        "bf_algo": "1. Map count.\n2. For x in nums: count[x]++, if count[x] > n/2 return x.",
        "bf_code": "#include <vector>\n#include <unordered_map>\n\nclass Solution {\npublic:\n    int majorityElement(const std::vector<int>& nums) {\n        std::unordered_map<int, int> counts;\n        for (int x : nums) {\n            if (++counts[x] > nums.size() / 2) return x;\n        }\n        return -1;\n    }\n};",
        "bf_tc": "O(N)", "bf_sc": "O(N)",
        "bf_why_not_opt": "Uses O(N) extra space. Boyer-Moore Voting algorithm achieves O(1) space.",
        "opt_pattern": "Boyer-Moore Voting Algorithm",
        "opt_concept": "Cancel out different elements. Majority element count exceeds rest combined.",
        "opt_obs": "Majority element always survives pair cancellations.",
        "opt_intuition": "Maintain candidate and count. Increment count if match, decrement if different. Reset candidate when count reaches 0.",
        "opt_algo": "1. candidate = 0, count = 0.\n2. For x in nums: if count==0 candidate=x; count += (x==candidate ? 1 : -1).\n3. Return candidate.",
        "opt_code": "#include <vector>\n\nclass Solution {\npublic:\n    int majorityElement(const std::vector<int>& nums) {\n        int candidate = 0, count = 0;\n        for (int num : nums) {\n            if (count == 0) candidate = num;\n            count += (num == candidate) ? 1 : -1;\n        }\n        return candidate;\n    }\n};",
        "opt_dry_run": "[2,2,1,1,1,2,2] -> candidate=2",
        "opt_tc": "O(N)", "opt_sc": "O(1)",
        "opt_why_opt": "Single pass O(N) time and O(1) auxiliary space.",
        "opt_mistakes": "Forgetting that majority element is guaranteed to exist > n/2.",
        "summary": "Find element with frequency > n/2 using Boyer-Moore Voting Algorithm.",
        "pattern_rec": "Element > n/2 frequency -> Boyer-Moore Voting.",
        "clues": "Majority element > n/2 guaranteed.",
        "diagram": "Cancel pairs of distinct elements -> winner is majority element.",
        "alt_sol": "Sorting: return nums[n/2] in O(N log N) time.",
        "edge_cases": "Single element array ([1] -> 1).",
        "tips": "Explain candidate cancellation logic.",
        "similar": "LeetCode #229, #1150, #136",
        "rev_notes": "Boyer-Moore: candidate & count. If count==0 candidate=x. O(N) time, O(1) space."
    },
    # 006
    {
        "dir": phase0_dir,
        "id": "006",
        "name": "Rotate Array",
        "lc_num": 189, "difficulty": "Medium",
        "url": "https://leetcode.com/problems/rotate-array/",
        "q_statement": "Given an integer array `nums`, rotate the array to the right by `k` steps, where `k` is non-negative.",
        "examples": "Input: nums = [1,2,3,4,5,6,7], k = 3\nOutput: [5,6,7,1,2,3,4]",
        "constraints": "- 1 <= nums.length <= 10^5\n- 0 <= k <= 10^5",
        "bf_pattern": "Auxiliary Array Allocation",
        "bf_intuition": "Copy elements to a new array at index (i + k) % n.",
        "bf_algo": "1. Create temp array of size n.\n2. temp[(i+k)%n] = nums[i].\n3. Copy temp back to nums.",
        "bf_code": "#include <vector>\n\nclass Solution {\npublic:\n    void rotate(std::vector<int>& nums, int k) {\n        int n = nums.size();
        std::vector<int> temp(n);
        for (int i = 0; i < n; ++i) temp[(i + k) % n] = nums[i];
        nums = temp;
    }\n};",
        "bf_tc": "O(N)", "bf_sc": "O(N)",
        "bf_why_not_opt": "Uses O(N) extra space. Rotation can be done in O(1) extra space using Array Reversal.",
        "opt_pattern": "Array Reversal Algorithm",
        "opt_concept": "Reversing sections of the array to achieve cyclic shift.",
        "opt_obs": "Rotating right by k is equivalent to reversing full array, then reversing first k elements, then remaining n-k elements.",
        "opt_intuition": "1. Reverse whole array [7,6,5,4,3,2,1]. 2. Reverse first k [5,6,7,4,3,2,1]. 3. Reverse remaining [5,6,7,1,2,3,4].",
        "opt_algo": "1. k = k % n.\n2. reverse(nums.begin(), nums.end()).\n3. reverse(nums.begin(), nums.begin() + k).\n4. reverse(nums.begin() + k, nums.end()).",
        "opt_code": "#include <vector>\n#include <algorithm>\n\nclass Solution {\npublic:\n    void rotate(std::vector<int>& nums, int k) {\n        int n = nums.size();\n        k %= n;\n        std::reverse(nums.begin(), nums.end());\n        std::reverse(nums.begin(), nums.begin() + k);\n        std::reverse(nums.begin() + k, nums.end());\n    }\n};",
        "opt_dry_run": "[1,2,3,4,5,6,7], k=3 -> Rev All:[7,6,5,4,3,2,1] -> Rev 0..2:[5,6,7,4,3,2,1] -> Rev 3..6:[5,6,7,1,2,3,4]",
        "opt_tc": "O(N)", "opt_sc": "O(1)",
        "opt_why_opt": "Reverses array three times in-place taking total O(N) time and O(1) space.",
        "opt_mistakes": "Forgetting k = k % n when k > n.",
        "summary": "Rotate array right by k steps using 3-step Array Reversal algorithm.",
        "pattern_rec": "Cyclic shift / Array Rotation -> Array Reversal Trick.",
        "clues": "In-place rotation with O(1) space constraint.",
        "diagram": "Reverse(All) -> Reverse(0..k-1) -> Reverse(k..n-1)",
        "alt_sol": "Cyclic Replacements (Jumping indices with GCD loop).",
        "edge_cases": "k=0, k >= n, n=1.",
        "tips": "Always remember k %= n at start.",
        "similar": "LeetCode #61: Rotate List, LeetCode #186: Reverse Words in a String II",
        "rev_notes": "k %= n. reverse(all), reverse(0..k), reverse(k..n). O(N) time, O(1) space."
    },
    # 007
    {
        "dir": phase0_dir,
        "id": "007",
        "name": "Move Zeroes",
        "lc_num": 283, "difficulty": "Easy",
        "url": "https://leetcode.com/problems/move-zeroes/",
        "q_statement": "Given an integer array `nums`, move all `0`'s to the end of it while maintaining the relative order of the non-zero elements in-place.",
        "examples": "Input: nums = [0,1,0,3,12]\nOutput: [1,3,12,0,0]",
        "constraints": "- 1 <= nums.length <= 10^4",
        "bf_pattern": "Extra Memory Copy",
        "bf_intuition": "Copy non-zero elements to a new array and pad zeros at the end.",
        "bf_algo": "1. Create temp vector.\n2. Copy non-zero elements.\n3. Fill remainder with zeros.",
        "bf_code": "#include <vector>\n\nclass Solution {\npublic:\n    void moveZeroes(std::vector<int>& nums) {\n        std::vector<int> temp;\n        for (int x : nums) if (x != 0) temp.push_back(x);\n        while (temp.size() < nums.size()) temp.push_back(0);\n        nums = temp;\n    }\n};",
        "bf_tc": "O(N)", "bf_sc": "O(N)",
        "bf_why_not_opt": "Uses O(N) auxiliary space. Can be done in-place with Two Pointers.",
        "opt_pattern": "Two Pointers (Read / Write)",
        "opt_concept": "Maintain write pointer for next non-zero element.",
        "opt_obs": "Non-zero elements can be swapped/copied forward to write_index position.",
        "opt_intuition": "Iterate read_pointer through array. Whenever nums[read_pointer] != 0, swap it with nums[write_pointer] and increment write_pointer.",
        "opt_algo": "1. write_index = 0.\n2. For read_index from 0 to n-1:\n   if nums[read_index] != 0: swap(nums[write_index++], nums[read_index]).",
        "opt_code": "#include <vector>\n#include <algorithm>\n\nclass Solution {\npublic:\n    void moveZeroes(std::vector<int>& nums) {\n        int write_index = 0;\n        for (int read_index = 0; read_index < nums.size(); ++read_index) {\n            if (nums[read_index] != 0) {\n                std::swap(nums[write_index++], nums[read_index]);\n            }\n        }\n    }\n};",
        "opt_dry_run": "[0,1,0,3,12] -> swap(nums[0], nums[1]) -> [1,0,0,3,12] -> ... -> [1,3,12,0,0]",
        "opt_tc": "O(N)", "opt_sc": "O(1)",
        "opt_why_opt": "Single pass in-place swaps, O(N) time and O(1) space.",
        "opt_mistakes": "Overwriting without swapping (leaving non-zero values duplicated if not padded correctly).",
        "summary": "Move zeroes to end in-place using two-pointer swap strategy.",
        "pattern_rec": "In-place partition / element filtering -> Two Pointers.",
        "clues": "Maintain relative order, in-place, zeroes at end.",
        "diagram": "[0, 1, 0, 3, 12] -> write=0, read=1 -> swap -> [1, 0, 0, 3, 12]",
        "alt_sol": "Copy non-zeroes to front, then loop to set remaining tail elements to 0.",
        "edge_cases": "No zeroes ([1,2,3]), all zeroes ([0,0,0]), single element.",
        "tips": "Emphasize minimize number of writes when array is mostly zeroes.",
        "similar": "LeetCode #27: Remove Element, LeetCode #26: Remove Duplicates",
        "rev_notes": "write_index = 0. For r=0..n-1: if nums[r]!=0 swap(nums[w++], nums[r]). O(N) time, O(1) space."
    },
    # 008
    {
        "dir": phase0_dir,
        "id": "008",
        "name": "Merge Sorted Array",
        "lc_num": 88, "difficulty": "Easy",
        "url": "https://leetcode.com/problems/merge-sorted-array/",
        "q_statement": "You are given two integer arrays `nums1` and `nums2`, sorted in non-decreasing order, and two integers `m` and `n`. Merge `nums2` into `nums1` as one sorted array in-place.",
        "examples": "Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3\nOutput: [1,2,2,3,5,6]",
        "constraints": "- nums1.length == m + n\n- nums2.length == n",
        "bf_pattern": "Concatenate and Sort",
        "bf_intuition": "Copy nums2 into the end of nums1 and call std::sort.",
        "bf_algo": "1. Copy nums2 into nums1[m...m+n-1].\n2. std::sort(nums1.begin(), nums1.end()).",
        "bf_code": "#include <vector>\n#include <algorithm>\n\nclass Solution {\npublic:\n    void merge(std::vector<int>& nums1, int m, std::vector<int>& nums2, int n) {\n        for (int i = 0; i < n; ++i) nums1[m + i] = nums2[i];\n        std::sort(nums1.begin(), nums1.end());\n    }\n};",
        "bf_tc": "O((M+N) log (M+N))", "bf_sc": "O(1)",
        "bf_why_not_opt": "Ignores the fact that both arrays are already individually sorted. Can merge in O(M+N) time.",
        "opt_pattern": "Three Pointers (Backward Merge)",
        "opt_concept": "Fill nums1 from the back (index m + n - 1) to avoid overwriting unread elements in nums1.",
        "opt_obs": "The back of nums1 has empty space reserved for elements, so merging largest to smallest from back prevents overwriting.",
        "opt_intuition": "Compare elements from the back of both arrays: `p1 = m - 1`, `p2 = n - 1`, `p = m + n - 1`. Place larger element at `nums1[p]` and decrement pointers.",
        "opt_algo": "1. p1 = m - 1, p2 = n - 1, p = m + n - 1.\n2. While p2 >= 0:\n   if p1 >= 0 and nums1[p1] > nums2[p2]: nums1[p--] = nums1[p1--]\n   else: nums1[p--] = nums2[p2--].",
        "opt_code": "#include <vector>\n\nclass Solution {\npublic:\n    void merge(std::vector<int>& nums1, int m, std::vector<int>& nums2, int n) {\n        int p1 = m - 1;\n        int p2 = n - 1;\n        int p = m + n - 1;\n        \n        while (p2 >= 0) {\n            if (p1 >= 0 && nums1[p1] > nums2[p2]) {\n                nums1[p--] = nums1[p1--];\n            } else {\n                nums1[p--] = nums2[p2--];\n            }\n        }\n    }\n};",
        "opt_dry_run": "nums1=[1,2,3,0,0,0], nums2=[2,5,6] -> compare 3 & 6 -> place 6 at index 5 -> ...",
        "opt_tc": "O(M + N)", "opt_sc": "O(1)",
        "opt_why_opt": "Linear time O(M+N) merge in-place without extra space.",
        "opt_mistakes": "Merging from front causing overwriting of nums1 elements, forgetting loop termination condition when nums1 exhausts first.",
        "summary": "Merge two sorted arrays in-place by filling nums1 backwards from index m+n-1.",
        "pattern_rec": "Merge sorted arrays in-place -> Backward Three Pointers.",
        "clues": "Pre-allocated buffer at end of nums1, both arrays sorted.",
        "diagram": "p1 at m-1, p2 at n-1, p at m+n-1. Fill largest elements backwards.",
        "alt_sol": "Forward merge into auxiliary vector of size m+n.",
        "edge_cases": "m=0 (nums1 empty), n=0 (nums2 empty).",
        "tips": "Emphasize backward fill logic to avoid buffer overwrite.",
        "similar": "LeetCode #21: Merge Two Sorted Lists, LeetCode #977: Squares of Sorted Array",
        "rev_notes": "p1=m-1, p2=n-1, p=m+n-1. While p2>=0: fill nums1[p--] with max(nums1[p1], nums2[p2]). O(M+N) time, O(1) space."
    },
    # 009
    {
        "dir": phase0_dir,
        "id": "009",
        "name": "Valid Anagram",
        "lc_num": 242, "difficulty": "Easy",
        "url": "https://leetcode.com/problems/valid-anagram/",
        "q_statement": "Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.",
        "examples": "Input: s = \"anagram\", t = \"nagaram\"\nOutput: true",
        "constraints": "- 1 <= s.length, t.length <= 5 * 10^4\n- s and t consist of lowercase English letters.",
        "bf_pattern": "String Sorting",
        "bf_intuition": "Sort both strings and check if they are identical.",
        "bf_algo": "1. If s.length() != t.length() return false.\n2. std::sort(s), std::sort(t).\n3. Return s == t.",
        "bf_code": "#include <string>\n#include <algorithm>\n\nclass Solution {\npublic:\n    bool isAnagram(std::string s, std::string t) {\n        if (s.length() != t.length()) return false;\n        std::sort(s.begin(), s.end());\n        std::sort(t.begin(), t.end());\n        return s == t;\n    }\n};",
        "bf_tc": "O(N log N)", "bf_sc": "O(1) or O(N)",
        "bf_why_not_opt": "Sorting takes O(N log N). Frequency array solves it in O(N) time.",
        "opt_pattern": "Frequency Array / Hash Map",
        "opt_concept": "Count char occurrences using fixed size frequency array of size 26.",
        "opt_obs": "Anagrams have identical character frequency counts.",
        "opt_intuition": "Increment count for characters in `s` and decrement for characters in `t`. All counts must end up at 0.",
        "opt_algo": "1. If s.length() != t.length() return false.\n2. int count[26] = {0}.\n3. For i=0..n-1: count[s[i]-'a']++, count[t[i]-'a']--.\n4. If any count[c] != 0 return false; return true.",
        "opt_code": "#include <string>\n#include <vector>\n\nclass Solution {\npublic:\n    bool isAnagram(const std::string& s, const std::string& t) {\n        if (s.length() != t.length()) return false;\n        int counts[26] = {0};\n        for (size_t i = 0; i < s.length(); ++i) {\n            counts[s[i] - 'a']++;\n            counts[t[i] - 'a']--;\n        }\n        for (int c : counts) {\n            if (c != 0) return false;\n        }\n        return true;\n    }\n};",
        "opt_dry_run": "s=\"anagram\", t=\"nagaram\" -> counts all balance to 0 -> true",
        "opt_tc": "O(N)", "opt_sc": "O(1)",
        "opt_why_opt": "Linear scan O(N) with constant O(1) extra space (26 integers).",
        "opt_mistakes": "Not checking length equality first, out-of-bounds array access for non-ASCII characters.",
        "summary": "Check if two strings are anagrams using a 26-element character frequency array.",
        "pattern_rec": "Character permutation / anagram check -> Frequency Array.",
        "clues": "Same length, reordered characters, lowercase English letters.",
        "diagram": "s adds counts, t subtracts counts -> check if all zero.",
        "alt_sol": "std::unordered_map for general Unicode character support.",
        "edge_cases": "Different lengths, single char strings.",
        "tips": "Mention Unicode follow-up: use std::unordered_map<char, int>.",
        "similar": "LeetCode #49: Group Anagrams, LeetCode #438: Find All Anagrams, LeetCode #567: Permutation in String",
        "rev_notes": "Length check. int counts[26]={0}. ++counts[s[i]-'a'], --counts[t[i]-'a']. Return all zeroes. O(N) time, O(1) space."
    },
    # 010
    {
        "dir": phase0_dir,
        "id": "010",
        "name": "Valid Palindrome",
        "lc_num": 125, "difficulty": "Easy",
        "url": "https://leetcode.com/problems/valid-palindrome/",
        "q_statement": "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward.",
        "examples": "Input: s = \"A man, a plan, a canal: Panama\"\nOutput: true",
        "constraints": "- 1 <= s.length <= 2 * 10^5",
        "bf_pattern": "Filtered Copy and Reverse",
        "bf_intuition": "Filter out non-alphanumeric chars into a clean string, lowercase it, and compare with its reverse.",
        "bf_algo": "1. Filter s to clean string filtered_s.\n2. std::string rev = filtered_s; reverse(rev).\n3. Return filtered_s == rev.",
        "bf_code": "#include <string>\n#include <algorithm>\n#include <cctype>\n\nclass Solution {\npublic:\n    bool isPalindrome(std::string s) {\n        std::string filtered = \"\";\n        for (char c : s) {\n            if (std::isalnum(c)) filtered += std::tolower(c);\n        }\n        std::string rev = filtered;\n        std::reverse(rev.begin(), rev.end());\n        return filtered == rev;\n    }\n};",
        "bf_tc": "O(N)", "bf_sc": "O(N)",
        "bf_why_not_opt": "Allocates extra memory for filtered and reversed strings. Two pointers solve in-place with O(1) memory.",
        "opt_pattern": "Two Pointers (Left / Right)",
        "opt_concept": "Compare characters from both ends using left and right pointers, skipping non-alphanumeric characters.",
        "opt_obs": "Palindrome reads same forward and backward. Non-alphanumeric chars can be skipped on the fly.",
        "opt_intuition": "Left pointer starts at 0, right at n-1. Advance left if non-alphanumeric, decrement right if non-alphanumeric. If both valid, compare lowercased characters.",
        "opt_algo": "1. left = 0, right = s.length() - 1.\n2. While left < right:\n   while left < right and !isalnum(s[left]): left++\n   while left < right and !isalnum(s[right]): right--\n   if tolower(s[left]) != tolower(s[right]): return false\n   left++; right--;\n3. Return true.",
        "opt_code": "#include <string>\n#include <cctype>\n\nclass Solution {\npublic:\n    bool isPalindrome(const std::string& s) {\n        int left = 0, right = s.length() - 1;\n        while (left < right) {\n            while (left < right && !std::isalnum(s[left])) left++;\n            while (left < right && !std::isalnum(s[right])) right--;\n            if (std::tolower(s[left]) != std::tolower(s[right])) return false;\n            left++;\n            right--;\n        }\n        return true;\n    }\n};",
        "opt_dry_run": "\"A man...Panama\" -> compares 'a' & 'a', 'm' & 'm', ... -> true",
        "opt_tc": "O(N)", "opt_sc": "O(1)",
        "opt_why_opt": "Single pass O(N) time and O(1) space without auxiliary string allocation.",
        "opt_mistakes": "Forgetting inner while bounds `left < right` causing out-of-bounds crashes on strings of all spaces/punctuation.",
        "summary": "Check valid palindrome ignoring non-alphanumeric characters using two pointers in O(N) time and O(1) space.",
        "pattern_rec": "Palindrome check on strings -> Two Pointers (Left / Right).",
        "clues": "Case-insensitive, ignore non-alphanumeric, read same forward and backward.",
        "diagram": "L -> [A man, a plan...] <- R (skipping spaces/commas)",
        "alt_sol": "Regex replace non-alphanumeric + string reverse.",
        "edge_cases": "Empty string/all spaces (\"   \" -> true), single char, no alphanumeric chars.",
        "tips": "Remember std::isalnum and std::tolower from <cctype>.",
        "similar": "LeetCode #680: Valid Palindrome II, LeetCode #234: Palindrome Linked List",
        "rev_notes": "left=0, right=n-1. Skip !isalnum. Compare tolower(s[left]) != tolower(s[right]). O(N) time, O(1) space."
    }
]

# Write Phase 0 problems
for p_data in all_problems:
    p_folder = os.path.join(p_data['dir'], f"{p_data['id']} {p_data['name']}")
    os.makedirs(p_folder, exist_ok=True)
    
    with open(os.path.join(p_folder, "00_Question.md"), "w", encoding="utf-8") as f:
        f.write(f"# {p_data['id']}. {p_data['name']}\n\n- **Platform**: LeetCode\n- **Problem Number**: #{p_data['lc_num']}\n- **Difficulty**: {p_data['difficulty']}\n- **URL**: [{p_data['name']}]({p_data['url']})\n\n---\n\n## Problem Statement\n\n{p_data['q_statement']}\n\n---\n\n## Examples\n\n{p_data['examples']}\n\n---\n\n## Constraints\n\n{p_data['constraints']}\n")
        
    with open(os.path.join(p_folder, "01_Brute_Force.md"), "w", encoding="utf-8") as f:
        f.write(f"# {p_data['name']}\n\n- **Problem Number**: {p_data['lc_num']}\n- **Platform**: LeetCode #{p_data['lc_num']}\n- **Difficulty**: {p_data['difficulty']}\n- **Pattern**: {p_data['bf_pattern']}\n\n---\n\n## Brute Force Intuition\n\n{p_data['bf_intuition']}\n\n---\n\n## Algorithm\n\n{p_data['bf_algo']}\n\n---\n\n## Code\n\n```cpp\n{p_data['bf_code']}\n```\n\n---\n\n## Time Complexity\n\n- **Time Complexity**: {p_data['bf_tc']}\n\n---\n\n## Space Complexity\n\n- **Space Complexity**: {p_data['bf_sc']}\n\n---\n\n## Why This Approach Is Not Optimal\n\n{p_data['bf_why_not_opt']}\n")

    with open(os.path.join(p_folder, "02_Optimal_Approach.md"), "w", encoding="utf-8") as f:
        f.write(f"# {p_data['name']}\n\n## Pattern Used\n\n- **Pattern**: **{p_data['opt_pattern']}**\n- **Concept**: {p_data['opt_concept']}\n\n---\n\n## Observation\n\n{p_data['opt_obs']}\n\n---\n\n## Intuition\n\n{p_data['opt_intuition']}\n\n---\n\n## Algorithm\n\n{p_data['opt_algo']}\n\n---\n\n## Clean C++17 Solution\n\n```cpp\n{p_data['opt_code']}\n```\n\n---\n\n## Dry Run\n\n{p_data['opt_dry_run']}\n\n---\n\n## Time Complexity\n\n- **Time Complexity**: {p_data['opt_tc']}\n\n---\n\n## Space Complexity\n\n- **Space Complexity**: {p_data['opt_sc']}\n\n---\n\n## Why This is Optimal\n\n{p_data['opt_why_opt']}\n\n---\n\n## Common Mistakes\n\n{p_data['opt_mistakes']}\n")

    with open(os.path.join(p_folder, "03_Explanation.md"), "w", encoding="utf-8") as f:
        f.write(f"# Problem Summary\n\n{p_data['summary']}\n\n---\n\n## Pattern Recognition\n\n{p_data['pattern_rec']}\n\n---\n\n## Important Clues\n\n{p_data['clues']}\n\n---\n\n## Example\n\n```text\n{p_data['diagram']}\n```\n\n---\n\n## Alternative Solutions\n\n{p_data['alt_sol']}\n\n---\n\n## Edge Cases\n\n{p_data['edge_cases']}\n\n---\n\n## Interview Tips\n\n{p_data['tips']}\n\n---\n\n## Similar Problems\n\n{p_data['similar']}\n\n---\n\n## Revision Notes\n\n{p_data['rev_notes']}\n")

print("Processed initial batch successfully!")
